SCALE Job started on ven. 02/08/2019 16:40:54
With Host name neutro-22
working directory /tmp/scale.promethee.29790
and process id 29790.
Input file named /tmp/plugin-Scale/src/test/cases.Scale-keno/godiva/godiva
and output file named /tmp/plugin-Scale/src/test/cases.Scale-keno/godiva/godiva.out
##########################################################
***Created 1 infinite homogeneous cells from unreferenced mixtures.
